(cl:defpackage pal_control_msgs-msg
  (:use )
  (:export
   "<ACTUATORCURRENTLIMIT>"
   "ACTUATORCURRENTLIMIT"
   "<MOTIONMANAGERFEEDBACK>"
   "MOTIONMANAGERFEEDBACK"
   "<MOTIONMANAGERGOAL>"
   "MOTIONMANAGERGOAL"
   "<MOTIONMANAGERRESULT>"
   "MOTIONMANAGERRESULT"
   "<MOTIONMANAGERACTION>"
   "MOTIONMANAGERACTION"
   "<MOTIONMANAGERACTIONGOAL>"
   "MOTIONMANAGERACTIONGOAL"
   "<MOTIONMANAGERACTIONFEEDBACK>"
   "MOTIONMANAGERACTIONFEEDBACK"
   "<MOTIONMANAGERACTIONRESULT>"
   "MOTIONMANAGERACTIONRESULT"
  ))

